### ISSUE TITLE
Add logo to front page on mobile

### ISSUE THREAD

**Issue by GeekPro101** [dowjcr/web-frontend#18]
One possible look:
![image](https://github.com/dowjcr/web-frontend/assets/14115426/d18b298c-f522-49c7-a143-7f486a98fa57)

**Comment by apple-phi** [comment]
Yeah, if we can find a way to do it that doesn't clutter the page too much I'd be open to adding this

**Comment by GeekPro101** [comment]
@apple-phi it's behind it and fairly transparent, so it feels like more of a background

**Comment by apple-phi** [comment]
In your demo it clashes with the text, we could consider the same idea but either smaller (to avoid the text) or with a higher opacity perhaps

**Comment by GeekPro101** [comment]
Smaller just looks odd, not sure how a higher opacity would help - that would surely decrease contrast?

**Comment by apple-phi** [comment]
Sorry, I meant higher transparency, lower opacity
