### ISSUE TITLE
ToC cut off to the right at certain sizes

### ISSUE THREAD

**Issue by GeekPro101** [dowjcr/web-frontend#19]
![image](https://github.com/dowjcr/web-frontend/assets/14115426/095c6ef1-a482-48f9-95c6-aa9cb504cbda)
At 1020px-1270px width, the right of the ToC is cut off

**Comment by apple-phi** [comment]
The layout for content pages needs to be reworked, currently it is in two columns who have fixed sizes based on screen size. A better approach would be to give the content the `flex` ability to `grow` and then put appropriate padding / margins around the ToC.

**Comment by GeekPro101** [comment]
@apple-phi have we considered using grid?

**Comment by apple-phi** [comment]
I think it already uses grid but with fixed columns sizes. Would need to set auto column sizing or do a flexbox grow, I think both approaches would do the same thing in this context
