### ISSUE TITLE
Consider using the same front page image for darkmode

### ISSUE THREAD

**Issue by GeekPro101** [dowjcr/web-frontend#30]
Related to #18 

Use the same colour as present darkmode, with the light mode image - would look something like this:
![image](https://github.com/dowjcr/web-frontend/assets/14115426/bb7ed8b4-bec3-4a80-be8e-a4f8f9911871)

**Comment by apple-phi** [comment]
Yeah I investigated this previously but I couldn't find a way to do it without being a bit jarring

**Comment by apple-phi** [comment]
I think the contrast between the magenta and the blue would need to be adjusted maybe

**Comment by GeekPro101** [comment]
@apple-phi I think it looks pretty good tbf, maybe a bit less contrasting?

**Comment by apple-phi** [comment]
Maybe. One idea I had that I didn't explore was to do an embossed effect so it's a bit more subtle, but I didn't finish the draft implementation

**Comment by GeekPro101** [comment]
@apple-phi  I did it with a slightly brighter colour - see my PR for the mobile icon for reference

**Comment by GeekPro101** [comment]
Closed by #54
