### ISSUE TITLE
Set title on homepage

### ISSUE THREAD

**Issue by GeekPro101** [dowjcr/web-frontend#31]
![image](https://github.com/dowjcr/web-frontend/assets/14115426/4d06a71e-1a48-4a1e-90e4-8d0d09ef2551)

No title set on homepage atm

**Comment by apple-phi** [comment]
Easy fix, just needs a `<svelte:head>` element to assign the title in `routes/+page.svelte`. Can I assign the PR to you @GeekPro101 ?
