### ISSUE TITLE
Consider making font smaller

### ISSUE THREAD

**Issue by GeekPro101** [dowjcr/web-frontend#32]
Atm the font is quite large - I think it feels a bit too big

**Comment by apple-phi** [comment]
Font where. On content pages?

**Comment by apple-phi** [comment]
Yeah possibly, pls can u PR committee page content one-size smaller and screenshot how it will look at a variety of screen sizes?

**Comment by GeekPro101** [comment]
Closed by c893b7e4be56f1953c8e99ef423e31349ff49274
